jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: marocchino/action-workflow_run-status@54b6e87d6cb552fc5f36dbe9a722a6048725917a
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
        submodules: recursive
    - continue-on-error: true
      name: Cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ github.workflow }}-${{ hashFiles('**/pom.xml')
          }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-${{ github.workflow }}

          '
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean test -fae -T 2 -B -V -DcloudBuild -Dmaven.wagon.http.retryHandler.count=3
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
    - continue-on-error: true
      if: always()
      name: Archive build artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Build debug files
        path: '**/target/rat.txt

          **/target/surefire-reports/*

          '
    - continue-on-error: true
      if: always()
      name: Surefire Report
      uses: mikepenz/action-junit-report@16a9560bd02f11e7e3bf6b3e2ef6bba6c9d07c32
      with:
        check_name: Test Report
        commit: ${{ github.event.workflow_run.head_sha }}
        detailed_summary: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        report_paths: '**/target/surefire-reports/TEST-*.xml'
    - continue-on-error: true
      if: always()
      name: Checkstyle report
      uses: cdapio/checkstyle-github-action@add_filter
      with:
        changed-since: ${{ github.event.workflow_run.pull_requests[0].base.ref }}
        commit: ${{ github.event.workflow_run.head_sha }}
        path: '**/checkstyle-result.xml'
name: Build with unit tests
on:
  repository_dispatch:
    types: trigger-ga___build.yml
