jobs:
  build:
    if: "github.event_name == 'workflow_dispatch' || github.event_name == 'push' ||\
      \ (contains(github.event.pull_request.labels.*.name, 'build')\n    && (github.event.action\
      \ != 'labeled' || github.event.label.name == 'build')\n    )\n"
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        path: plugin
    - continue-on-error: true
      id: filter
      if: github.event_name != 'workflow_dispatch' && github.event_name != 'push'
      uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
      with:
        filters: "e2e-test:\n  - '**/e2e-test/**'\n"
        working-directory: plugin
    - continue-on-error: true
      name: Checkout e2e test repo
      uses: actions/checkout@v3
      with:
        path: e2e
        repository: cdapio/cdap-e2e-tests
    - continue-on-error: true
      name: Cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ github.workflow }}-${{ hashFiles('**/pom.xml')
          }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-${{ github.workflow }}

          '
    - continue-on-error: true
      if: github.event_name != 'workflow_dispatch' && github.event_name != 'push'
        && steps.filter.outputs.e2e-test == 'false'
      name: Run required e2e tests
      run: python3 e2e/src/main/scripts/run_cdap_e2e_test.py --testRunner TestRunnerRequired.java
        --cdapBranch "${{ github.event.pull_request.base.ref }}"
    - continue-on-error: true
      if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        || steps.filter.outputs.e2e-test == 'true'
      name: Run all e2e tests
      run: python3 e2e/src/main/scripts/run_cdap_e2e_test.py --testRunner TestRunnerRequired.java
        --cdapBranch "${{ github.event.pull_request.base.ref }}"
    - continue-on-error: true
      if: always()
      name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: Cucumber report - ${{ matrix.tests }}
        path: ./plugin/${{ matrix.tests }}/target/cucumber-reports
    - continue-on-error: true
      if: always()
      name: Upload debug files
      uses: actions/upload-artifact@v3
      with:
        name: Debug files - ${{ matrix.tests }}
        path: ./**/target/e2e-debug
    - continue-on-error: true
      if: always()
      name: Upload files to GCS
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        destination: e2e-tests-cucumber-reports/${{ github.event.repository.name }}/${{
          github.ref }}
        path: ./plugin/cdap-e2e-tests/target/cucumber-reports
    strategy:
      fail-fast: false
      matrix:
        tests:
        - cdap-e2e-tests
name: Build e2e tests
on:
  repository_dispatch:
    types: trigger-ga___e2e.yml
