jobs:
  report:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Write result to BigQuery
      run: 'echo ''{ "repository": "${{ github.repository }}", "build_name": "${{
        github.event.workflow.name }}", "branch": "${{ github.event.workflow_run.head_branch
        }}", "conclusion": "${{ github.event.workflow_run.conclusion }}", "started_at":
        "${{ github.event.workflow_run.created_at }}", "ended_at": "${{ github.event.workflow_run.updated_at
        }}", "url": "${{ github.event.workflow_run.html_url }}", "run_id": "${{ github.event.workflow_run.id
        }}", "run_attempt": "${{ github.event.workflow_run.run_attempt }}" }'' | bq
        insert ${{ vars.BUILD_HISTORY_TABLE }}

        '
name: Report Build Result
on:
  repository_dispatch:
    types: trigger-ga___report-build-result.yml
