jobs:
  trigger:
    if: "github.event_name == 'workflow_dispatch' || github.event_name == 'push' ||\
      \ (contains(github.event.pull_request.labels.*.name, 'build')\n   && (github.event.action\
      \ != 'labeled' || github.event.label.name == 'build')\n   )\n"
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Trigger build
      run: echo Maven build will be triggered now
name: Trigger build
on:
  repository_dispatch:
    types: trigger-ga___trigger.yml
